<?php

include_once('forPages.php');

$page = new Page('dimentions.php');
$page->title = 'Hello, world!';
?>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec in leo condimentum, rutrum neque sit amet, suscipit velit. Donec egestas vestibulum elit a interdum. Donec et tellus sed elit tincidunt posuere ut at lorem. Cras lacinia, odio et accumsan volutpat, dolor lorem semper mi, in consequat lorem diam non urna. Duis sagittis sed nunc id volutpat. Phasellus mauris ante, varius sit amet diam vel, dapibus convallis augue. Duis pretium pellentesque mi. Fusce vestibulum lorem id fermentum dignissim. Suspendisse at tortor quam. Praesent eu ullamcorper tellus. Suspendisse blandit dolor vehicula, venenatis orci id, interdum arcu. Ut non porta urna, non fermentum urna. Nulla quis mi gravida, varius augue eget, ultricies lorem. Proin sed sagittis nulla, et semper nunc. Praesent vitae nulla magna.

<p>Etiam condimentum augue at erat iaculis sollicitudin. In ut tincidunt mauris. Donec malesuada ornare nisi, sit amet faucibus felis dictum vitae. Donec in risus at tellus rutrum aliquam in vitae enim. Nullam odio mi, aliquam a nulla vitae, mattis mattis ante. Nunc interdum mi in mi faucibus luctus. Integer eleifend quam eget est pellentesque accumsan. Curabitur egestas a orci a facilisis. Aenean ut lacus neque. Morbi dignissim, purus eu suscipit sodales, lacus ligula auctor leo, sed tempus lectus justo non dui. Vivamus ac semper est. Sed gravida est enim, vitae condimentum lectus tincidunt pharetra. Etiam congue nulla nec libero cursus cursus.

<p>Mauris tempor, nibh a porta dignissim, nulla nunc posuere elit, non fringilla metus sem ut ligula. Curabitur nec mauris fermentum, consequat turpis a, porttitor ante. Nam tortor dolor, consectetur vel neque faucibus, blandit mattis velit. Fusce justo lacus, egestas sed urna vitae, ornare congue sapien. Aliquam nec mauris at mauris molestie vulputate. Praesent ut orci id ipsum lacinia pharetra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

<p>Sed sit amet neque blandit metus tincidunt suscipit. Vivamus sed nibh at ligula venenatis aliquam. Nunc a odio purus. Donec viverra malesuada aliquam. Nam sagittis erat non risus gravida viverra. Proin feugiat at mauris nec mattis. Nam vel elementum nulla. Donec et tortor pretium, sodales nibh vel, hendrerit elit. Donec dignissim, felis ut tincidunt aliquam, nisi nunc tempor mauris, in gravida ipsum mi eget turpis. Sed vitae elementum nunc. Proin iaculis ligula ut lorem egestas pellentesque. Fusce facilisis eros adipiscing tellus aliquet, vitae hendrerit lorem commodo. Phasellus suscipit luctus eros eu sodales. Praesent faucibus felis diam. Fusce pulvinar eros augue, id euismod massa sollicitudin non. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

<p>In quis odio justo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vehicula porta augue a tincidunt. Sed suscipit sem ac scelerisque hendrerit. Cras libero arcu, elementum faucibus luctus at, sollicitudin eu est. Vestibulum eget est diam. Phasellus et volutpat sapien. Praesent dapibus iaculis neque, id sodales enim. Vestibulum ac purus arcu. Curabitur ut ante tellus. Maecenas ullamcorper purus a orci placerat imperdiet. Suspendisse potenti. Donec pretium nisl magna, vel accumsan lacus eleifend et. Sed at ligula nibh.